language: python
python:
  - 2.6
  - 2.7
install:
    - pip install coveralls --use-mirrors
    - pip install .
script:
    - coverage run --source=devproxy `which trial` devproxy
after_success:
    - coveralls
